services:
  web:
    build: .
    depends_on:
      - backend
      - nginx

  backend:
    image: leogloriainfnet/cars:2.0-linux
    ports:
      - "8080:8080"

  nginx:
    build:
      context: .
      target: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - backend
